# Generated by Django 4.0.4 on 2022-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_id', models.BigIntegerField()),
                ('tweet_text', models.CharField(max_length=300)),
            ],
        ),
    ]
