# Generated by Django 4.0.4 on 2022-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_1', '0002_alter_tweets_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='tweet_clean',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
