# Generated by Django 4.0.4 on 2022-06-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_1', '0003_tweets_tweet_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='sentiment_done',
            field=models.BinaryField(default=False),
        ),
    ]
