# Generated by Django 4.0.4 on 2022-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_1', '0005_alter_tweets_sentiment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
