# Generated by Django 4.0.4 on 2022-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_1', '0006_tweets_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='ens1_score',
            field=models.FloatField(default=0),
        ),
    ]
