# Generated by Django 4.0.4 on 2022-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
