# Generated by Django 4.0.4 on 2022-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='l1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='l2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='neg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='pos_count',
            field=models.IntegerField(default=0),
        ),
    ]
