# Generated by Django 4.0.4 on 2022-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_2', '0002_authors_l1_authors_l1_done_authors_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='l3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='l3_done',
            field=models.BooleanField(default=False),
        ),
    ]
