# Generated by Django 4.0.4 on 2022-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_2', '0003_authors_l3_authors_l3_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='ens1_count',
            field=models.IntegerField(default=0),
        ),
    ]
