# Generated by Django 4.0.4 on 2022-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_2', '0004_authors_ens1_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='ens1_count',
            new_name='anger_count',
        ),
        migrations.AddField(
            model_name='authors',
            name='joy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='optimism_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='sadness_count',
            field=models.IntegerField(default=0),
        ),
    ]
